
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-25T16:35:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfbb8321efd1006d3c8ed6b250e4c8930d80f95a",
 "version": "4.2.4+6.gdfbb832"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
